menu:
  About: /about/
  Archives: /archives/
  Advice: /categories/advice/
  Drinks: /categories/drinks/
  Healthful: /categories/healthful/
  The Kitchen: /categories/the-kitchen/
  Travel F&B: /categories/travel-f-b/

widgets:
- search
- recent_posts
- category
#- tagcloud

excerpt_link: Read More ›

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
